### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Raspipython** [rm-hull/luma.led_matrix#262] opened 2021-11-20 09:57 UTC
Im new at github , and i tryed downloaded the luma led matrix files for my raspberry pi 3.
when i typed:
 sudo pip3 install luma.led_matrix,
the rasperry pi tryed to build a wheel and than, thiss error appered:

  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mfnqdj3_
       cwd: /tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/
  Complete output (161 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.9
  copying ws2812.py -> build/lib.linux-armv7l-3.9
  running build_ext
  building '_ws2812' extension
  creating build/temp.linux-armv7l-3.9
  creating build/temp.linux-armv7l-3.9/lib
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilib/ -I/usr/include/python3.9 -c lib/ws2812-RPi.c -o build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o
  In file included from lib/ws2812-RPi.c:1:
  lib/ws2812-RPi.h:95:1: warning: multi-line comment [-Wcomment]
     95 | // |   |   |  \  \___|  |_|  |  / /_/ \  ___/ \___ \
        | ^
  In file included from lib/ws2812-RPi.c:1:
  lib/ws2812-RPi.h:123:1: warning: multi-line comment [-Wcomment]
    123 | //  |    `   \  ___/|  |  |  |   |  \  ___/ \___ \  /  <_\ \/   \     /  / __ \|  | \/\___ \
        | ^
  lib/ws2812-RPi.h:389:1: warning: multi-line comment [-Wcomment]
    389 | // |    |    \_   _____/\______ \    /   _____//  |_ __ ___/ ____\/ ____\
        | ^
  lib/ws2812-RPi.h:436:1: warning: multi-line comment [-Wcomment]
    436 | //  |    |  \_/ __ \| __ \|  |  \/ ___\
        | ^
  lib/ws2812-RPi.h:456:1: warning: multi-line comment [-Wcomment]
    456 | // |   |/    \|  \   __\ /    ~    \__  \\_  __ \/ __ |\ \/ \/ /\__  \\_  __ \_/ __ \
        | ^
  lib/ws2812-RPi.h:470:1: warning: multi-line comment [-Wcomment]
    470 | //  |    |  / |  |_> > /_/ | / __ \|  | \  ___/  |    |___  |        \ |    `   \\___ \
        | ^
  lib/ws2812-RPi.h:481:1: warning: multi-line comment [-Wcomment]
    481 | //  |        \|  |   |  | \  ___/\  \___|  |  \___ \
        | ^
  lib/ws2812-RPi.c: In function ‘reverseWord’:
  lib/ws2812-RPi.c:49:16: warning: variable ‘bit’ set but not used [-Wunused-but-set-variable]
     49 |  unsigned char bit;
        |                ^~~
  lib/ws2812-RPi.c: In function ‘mem_phys_to_virt’:
  lib/ws2812-RPi.c:119:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
    119 |  for (i = 0; i < NUM_PAGES; i++) {
        |                ^
  lib/ws2812-RPi.c: At top level:
  lib/ws2812-RPi.c:147:1: warning: multi-line comment [-Wcomment]
    147 | // |    |    \_   _____/\______ \    /   _____//  |_ __ ___/ ____\/ ____\
        | ^
  lib/ws2812-RPi.c:292:1: warning: multi-line comment [-Wcomment]
    292 | //  |    |  \_/ __ \| __ \|  |  \/ ___\
        | ^
  lib/ws2812-RPi.c:471:1: warning: multi-line comment [-Wcomment]
    471 | // |   |/    \|  \   __\ /    ~    \__  \\_  __ \/ __ |\ \/ \/ /\__  \\_  __ \_/ __ \
        | ^
  lib/ws2812-RPi.c: In function ‘initHardware’:
  lib/ws2812-RPi.c:552:56: warning: comparison of integer expressions of different signedness: ‘__off_t’ {aka ‘long int’} and ‘long unsigned int’ [-Wsign-compare]
    552 |  if (lseek(fd, (unsigned long)virtbase >> 9, SEEK_SET) != (unsigned long)virtbase >> 9) {
        |                                                        ^~
  lib/ws2812-RPi.c:557:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
    557 |  for (i = 0; i < NUM_PAGES; i++) {
        |                ^
  lib/ws2812-RPi.c:569:18: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses]
    569 |   if ((pfn >> 55)&0xfbf != 0x10c) {  // pagemap bits: https://www.kernel.org/doc/Documentation/vm/pagemap.txt
        |                  ^
  lib/ws2812-RPi.c: At top level:
  lib/ws2812-RPi.c:745:1: warning: multi-line comment [-Wcomment]
    745 | //  |    |  / |  |_> > /_/ | / __ \|  | \  ___/  |    |___  |        \ |    `   \\___ \
        | ^
  lib/ws2812-RPi.c: In function ‘show’:
  lib/ws2812-RPi.c:764:12: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
    764 |  for(i=0; i<numLEDs; i++) {
        |            ^
  lib/ws2812-RPi.c:801:15: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
    801 |  for(i = 0; i < (cbp->length / 4); i++) {
        |               ^
  lib/ws2812-RPi.c:829:1: warning: "/*" within comment [-Wcomment]
    829 | /**/
        |
  lib/ws2812-RPi.c:762:10: warning: unused variable ‘color’ [-Wunused-variable]
    762 |  Color_t color;
        |          ^~~~~
  lib/ws2812-RPi.c:758:15: warning: unused variable ‘PWMWaveformBitPos’ [-Wunused-variable]
    758 |  unsigned int PWMWaveformBitPos = 0;
        |               ^~~~~~~~~~~~~~~~~
  lib/ws2812-RPi.c:757:15: warning: unused variable ‘LEDBuffeWordPos’ [-Wunused-variable]
    757 |  unsigned int LEDBuffeWordPos = 0;
        |               ^~~~~~~~~~~~~~~
  lib/ws2812-RPi.c: At top level:
  lib/ws2812-RPi.c:839:1: warning: multi-line comment [-Wcomment]
    839 | //  |        \|  |   |  | \  ___/\  \___|  |  \___ \
        | ^
  lib/ws2812-RPi.c: In function ‘theaterChaseRainbow’:
  lib/ws2812-RPi.c:921:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
    921 |    for (i=0; i < numPixels(); i=i+3) {
        |                ^
  lib/ws2812-RPi.c:928:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
    928 |    for (i=0; i < numPixels(); i=i+3) {
        |                ^
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilib/ -I/usr/include/python3.9 -c ws2812-RPi_wrap.c -o build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o
  In file included from ws2812-RPi_wrap.c:2967:
  lib/ws2812-RPi.h:95:1: warning: multi-line comment [-Wcomment]
     95 | // |   |   |  \  \___|  |_|  |  / /_/ \  ___/ \___ \
        | ^
  In file included from ws2812-RPi_wrap.c:2967:
  lib/ws2812-RPi.h:123:1: warning: multi-line comment [-Wcomment]
    123 | //  |    `   \  ___/|  |  |  |   |  \  ___/ \___ \  /  <_\ \/   \     /  / __ \|  | \/\___ \
        | ^
  lib/ws2812-RPi.h:389:1: warning: multi-line comment [-Wcomment]
    389 | // |    |    \_   _____/\______ \    /   _____//  |_ __ ___/ ____\/ ____\
        | ^
  lib/ws2812-RPi.h:436:1: warning: multi-line comment [-Wcomment]
    436 | //  |    |  \_/ __ \| __ \|  |  \/ ___\
        | ^
  lib/ws2812-RPi.h:456:1: warning: multi-line comment [-Wcomment]
    456 | // |   |/    \|  \   __\ /    ~    \__  \\_  __ \/ __ |\ \/ \/ /\__  \\_  __ \_/ __ \
        | ^
  lib/ws2812-RPi.h:470:1: warning: multi-line comment [-Wcomment]
    470 | //  |    |  / |  |_> > /_/ | / __ \|  | \  ___/  |    |___  |        \ |    `   \\___ \
        | ^
  lib/ws2812-RPi.h:481:1: warning: multi-line comment [-Wcomment]
    481 | //  |        \|  |   |  | \  ___/\  \___|  |  \___ \
        | ^
  ws2812-RPi_wrap.c: In function ‘PyInit__ws2812’:
  ws2812-RPi_wrap.c:4722:21: warning: variable ‘md’ set but not used [-Wunused-but-set-variable]
   4722 |   PyObject *m, *d, *md;
        |                     ^~
  In file included from ws2812-RPi_wrap.c:2967:
  At top level:
  lib/ws2812-RPi.h:359:31: warning: ‘ctl’ defined but not used [-Wunused-variable]
    359 | static struct control_data_s *ctl;
        |                               ^~~
  lib/ws2812-RPi.h:341:31: warning: ‘gpio_reg’ defined but not used [-Wunused-variable]
    341 | static volatile unsigned int *gpio_reg;  // GPIO pin controller register set
        |                               ^~~~~~~~
  lib/ws2812-RPi.h:340:31: warning: ‘dma_reg’ defined but not used [-Wunused-variable]
    340 | static volatile unsigned int *dma_reg;  // DMA controller register set
        |                               ^~~~~~~
  lib/ws2812-RPi.h:339:31: warning: ‘clk_reg’ defined but not used [-Wunused-variable]
    339 | static volatile unsigned int *clk_reg;  // PWM clock manager register set
        |                               ^~~~~~~
  lib/ws2812-RPi.h:338:31: warning: ‘pwm_reg’ defined but not used [-Wunused-variable]
    338 | static volatile unsigned int *pwm_reg;  // PWM controller register set
        |                               ^~~~~~~
  lib/ws2812-RPi.h:336:17: warning: ‘virtbase’ defined but not used [-Wunused-variable]
    336 | static uint8_t *virtbase;     // Pointer to some virtual memory that will be allocated
        |                 ^~~~~~~~
  In file included from /usr/include/string.h:495,
                   from /usr/include/python3.9/Python.h:30,
                   from ws2812-RPi_wrap.c:125:
  In function ‘strncpy’,
      inlined from ‘SWIG_Python_FixMethods’ at ws2812-RPi_wrap.c:4692:15,
      inlined from ‘PyInit__ws2812’ at ws2812-RPi_wrap.c:4790:3:
  /usr/include/arm-linux-gnueabihf/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output truncated before terminating nul copying 10 bytes from a string of the same length [-Wstringop-truncation]
    106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o -Llib/ -o build/lib.linux-armv7l-3.9/_ws2812.cpython-39-arm-linux-gnueabihf.so
  /usr/bin/ld: build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:415: multiple definition of `PWMWaveform'; build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:415: first defined here
  /usr/bin/ld: build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:410: multiple definition of `LEDBuffer'; build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:410: first defined here
  /usr/bin/ld: build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:407: multiple definition of `numLEDs'; build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:407: first defined here
  /usr/bin/ld: build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:398: multiple definition of `brightness'; build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:398: first defined here
  /usr/bin/ld: build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:335: multiple definition of `page_map'; build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:335: first defined here
  collect2: error: ld returned 1 exit status
  error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for ws2812

then he wrote:

  Running setup.py clean for ws2812
Failed to build ws2812
Installing collected packages: ws2812, rpi-ws281x, luma.led-matrix
    Running setup.py install for ws2812 ... error
and then this error apperd:

   ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-e7hbzxpn/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/ws2812
         cwd: /tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/
    Complete output (163 lines):
    running install
    /usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.9
    copying ws2812.py -> build/lib.linux-armv7l-3.9
    running build_ext
    building '_ws2812' extension
    creating build/temp.linux-armv7l-3.9
    creating build/temp.linux-armv7l-3.9/lib
    arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilib/ -I/usr/include/python3.9 -c lib/ws2812-RPi.c -o build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o
    In file included from lib/ws2812-RPi.c:1:
    lib/ws2812-RPi.h:95:1: warning: multi-line comment [-Wcomment]
       95 | // |   |   |  \  \___|  |_|  |  / /_/ \  ___/ \___ \
          | ^
    In file included from lib/ws2812-RPi.c:1:
    lib/ws2812-RPi.h:123:1: warning: multi-line comment [-Wcomment]
      123 | //  |    `   \  ___/|  |  |  |   |  \  ___/ \___ \  /  <_\ \/   \     /  / __ \|  | \/\___ \
          | ^
    lib/ws2812-RPi.h:389:1: warning: multi-line comment [-Wcomment]
      389 | // |    |    \_   _____/\______ \    /   _____//  |_ __ ___/ ____\/ ____\
          | ^
    lib/ws2812-RPi.h:436:1: warning: multi-line comment [-Wcomment]
      436 | //  |    |  \_/ __ \| __ \|  |  \/ ___\
          | ^
    lib/ws2812-RPi.h:456:1: warning: multi-line comment [-Wcomment]
      456 | // |   |/    \|  \   __\ /    ~    \__  \\_  __ \/ __ |\ \/ \/ /\__  \\_  __ \_/ __ \
          | ^
    lib/ws2812-RPi.h:470:1: warning: multi-line comment [-Wcomment]
      470 | //  |    |  / |  |_> > /_/ | / __ \|  | \  ___/  |    |___  |        \ |    `   \\___ \
          | ^
    lib/ws2812-RPi.h:481:1: warning: multi-line comment [-Wcomment]
      481 | //  |        \|  |   |  | \  ___/\  \___|  |  \___ \
          | ^
    lib/ws2812-RPi.c: In function ‘reverseWord’:
    lib/ws2812-RPi.c:49:16: warning: variable ‘bit’ set but not used [-Wunused-but-set-variable]
       49 |  unsigned char bit;
          |                ^~~
    lib/ws2812-RPi.c: In function ‘mem_phys_to_virt’:
    lib/ws2812-RPi.c:119:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      119 |  for (i = 0; i < NUM_PAGES; i++) {
          |                ^
    lib/ws2812-RPi.c: At top level:
    lib/ws2812-RPi.c:147:1: warning: multi-line comment [-Wcomment]
      147 | // |    |    \_   _____/\______ \    /   _____//  |_ __ ___/ ____\/ ____\
          | ^
    lib/ws2812-RPi.c:292:1: warning: multi-line comment [-Wcomment]
      292 | //  |    |  \_/ __ \| __ \|  |  \/ ___\
          | ^
    lib/ws2812-RPi.c:471:1: warning: multi-line comment [-Wcomment]
      471 | // |   |/    \|  \   __\ /    ~    \__  \\_  __ \/ __ |\ \/ \/ /\__  \\_  __ \_/ __ \
          | ^
    lib/ws2812-RPi.c: In function ‘initHardware’:
    lib/ws2812-RPi.c:552:56: warning: comparison of integer expressions of different signedness: ‘__off_t’ {aka ‘long int’} and ‘long unsigned int’ [-Wsign-compare]
      552 |  if (lseek(fd, (unsigned long)virtbase >> 9, SEEK_SET) != (unsigned long)virtbase >> 9) {
          |                                                        ^~
    lib/ws2812-RPi.c:557:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      557 |  for (i = 0; i < NUM_PAGES; i++) {
          |                ^
    lib/ws2812-RPi.c:569:18: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses]
      569 |   if ((pfn >> 55)&0xfbf != 0x10c) {  // pagemap bits: https://www.kernel.org/doc/Documentation/vm/pagemap.txt
          |                  ^
    lib/ws2812-RPi.c: At top level:
    lib/ws2812-RPi.c:745:1: warning: multi-line comment [-Wcomment]
      745 | //  |    |  / |  |_> > /_/ | / __ \|  | \  ___/  |    |___  |        \ |    `   \\___ \
          | ^
    lib/ws2812-RPi.c: In function ‘show’:
    lib/ws2812-RPi.c:764:12: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      764 |  for(i=0; i<numLEDs; i++) {
          |            ^
    lib/ws2812-RPi.c:801:15: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      801 |  for(i = 0; i < (cbp->length / 4); i++) {
          |               ^
    lib/ws2812-RPi.c:829:1: warning: "/*" within comment [-Wcomment]
      829 | /**/
          |
    lib/ws2812-RPi.c:762:10: warning: unused variable ‘color’ [-Wunused-variable]
      762 |  Color_t color;
          |          ^~~~~
    lib/ws2812-RPi.c:758:15: warning: unused variable ‘PWMWaveformBitPos’ [-Wunused-variable]
      758 |  unsigned int PWMWaveformBitPos = 0;
          |               ^~~~~~~~~~~~~~~~~
    lib/ws2812-RPi.c:757:15: warning: unused variable ‘LEDBuffeWordPos’ [-Wunused-variable]
      757 |  unsigned int LEDBuffeWordPos = 0;
          |               ^~~~~~~~~~~~~~~
    lib/ws2812-RPi.c: At top level:
    lib/ws2812-RPi.c:839:1: warning: multi-line comment [-Wcomment]
      839 | //  |        \|  |   |  | \  ___/\  \___|  |  \___ \
          | ^
    lib/ws2812-RPi.c: In function ‘theaterChaseRainbow’:
    lib/ws2812-RPi.c:921:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      921 |    for (i=0; i < numPixels(); i=i+3) {
          |                ^
    lib/ws2812-RPi.c:928:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      928 |    for (i=0; i < numPixels(); i=i+3) {
          |                ^
    arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilib/ -I/usr/include/python3.9 -c ws2812-RPi_wrap.c -o build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o
    In file included from ws2812-RPi_wrap.c:2967:
    lib/ws2812-RPi.h:95:1: warning: multi-line comment [-Wcomment]
       95 | // |   |   |  \  \___|  |_|  |  / /_/ \  ___/ \___ \
          | ^
    In file included from ws2812-RPi_wrap.c:2967:
    lib/ws2812-RPi.h:123:1: warning: multi-line comment [-Wcomment]
      123 | //  |    `   \  ___/|  |  |  |   |  \  ___/ \___ \  /  <_\ \/   \     /  / __ \|  | \/\___ \
          | ^
    lib/ws2812-RPi.h:389:1: warning: multi-line comment [-Wcomment]
      389 | // |    |    \_   _____/\______ \    /   _____//  |_ __ ___/ ____\/ ____\
          | ^
    lib/ws2812-RPi.h:436:1: warning: multi-line comment [-Wcomment]
      436 | //  |    |  \_/ __ \| __ \|  |  \/ ___\
          | ^
    lib/ws2812-RPi.h:456:1: warning: multi-line comment [-Wcomment]
      456 | // |   |/    \|  \   __\ /    ~    \__  \\_  __ \/ __ |\ \/ \/ /\__  \\_  __ \_/ __ \
          | ^
    lib/ws2812-RPi.h:470:1: warning: multi-line comment [-Wcomment]
      470 | //  |    |  / |  |_> > /_/ | / __ \|  | \  ___/  |    |___  |        \ |    `   \\___ \
          | ^
    lib/ws2812-RPi.h:481:1: warning: multi-line comment [-Wcomment]
      481 | //  |        \|  |   |  | \  ___/\  \___|  |  \___ \
          | ^
    ws2812-RPi_wrap.c: In function ‘PyInit__ws2812’:
    ws2812-RPi_wrap.c:4722:21: warning: variable ‘md’ set but not used [-Wunused-but-set-variable]
     4722 |   PyObject *m, *d, *md;
          |                     ^~
    In file included from ws2812-RPi_wrap.c:2967:
    At top level:
    lib/ws2812-RPi.h:359:31: warning: ‘ctl’ defined but not used [-Wunused-variable]
      359 | static struct control_data_s *ctl;
          |                               ^~~
    lib/ws2812-RPi.h:341:31: warning: ‘gpio_reg’ defined but not used [-Wunused-variable]
      341 | static volatile unsigned int *gpio_reg;  // GPIO pin controller register set
          |                               ^~~~~~~~
    lib/ws2812-RPi.h:340:31: warning: ‘dma_reg’ defined but not used [-Wunused-variable]
      340 | static volatile unsigned int *dma_reg;  // DMA controller register set
          |                               ^~~~~~~
    lib/ws2812-RPi.h:339:31: warning: ‘clk_reg’ defined but not used [-Wunused-variable]
      339 | static volatile unsigned int *clk_reg;  // PWM clock manager register set
          |                               ^~~~~~~
    lib/ws2812-RPi.h:338:31: warning: ‘pwm_reg’ defined but not used [-Wunused-variable]
      338 | static volatile unsigned int *pwm_reg;  // PWM controller register set
          |                               ^~~~~~~
    lib/ws2812-RPi.h:336:17: warning: ‘virtbase’ defined but not used [-Wunused-variable]
      336 | static uint8_t *virtbase;     // Pointer to some virtual memory that will be allocated
          |                 ^~~~~~~~
    In file included from /usr/include/string.h:495,
                     from /usr/include/python3.9/Python.h:30,
                     from ws2812-RPi_wrap.c:125:
    In function ‘strncpy’,
        inlined from ‘SWIG_Python_FixMethods’ at ws2812-RPi_wrap.c:4692:15,
        inlined from ‘PyInit__ws2812’ at ws2812-RPi_wrap.c:4790:3:
    /usr/include/arm-linux-gnueabihf/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output truncated before terminating nul copying 10 bytes from a string of the same length [-Wstringop-truncation]
      106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o -Llib/ -o build/lib.linux-armv7l-3.9/_ws2812.cpython-39-arm-linux-gnueabihf.so
    /usr/bin/ld: build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:415: multiple definition of `PWMWaveform'; build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:415: first defined here
    /usr/bin/ld: build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:410: multiple definition of `LEDBuffer'; build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:410: first defined here
    /usr/bin/ld: build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:407: multiple definition of `numLEDs'; build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:407: first defined here
    /usr/bin/ld: build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:398: multiple definition of `brightness'; build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:398: first defined here
    /usr/bin/ld: build/temp.linux-armv7l-3.9/ws2812-RPi_wrap.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:335: multiple definition of `page_map'; build/temp.linux-armv7l-3.9/lib/ws2812-RPi.o:/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/lib/ws2812-RPi.h:335: first defined here
    collect2: error: ld returned 1 exit status
    error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vgchcs52/ws2812_bd9b1977576342208e129167056d18b6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-e7hbzxpn/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/ws2812 Check the logs for full command output.

i hope you can help me.
sorry for my bad english (-:

**Comment by thijstriemstra** [comment] 2021-11-20 11:10
Duplicate of #260

**Closed by thijstriemstra** 2021-11-20 11:10 UTC
