### ISSUE TITLE
luma.led_matrix not working on ZeroSeg 7-segment device after "Bullseye" install

### ISSUE THREAD

**Issue by linuxminty** [rm-hull/luma.led_matrix#265] opened 2021-12-02 00:27 UTC
#### Type of Raspberry Pi
Model 4B, 2GB

#### Linux Kernel version
Linux raspberrypi-4B 5.10.63-v7l+ #1488 SMP Thu Nov 18 16:15:28 GMT 2021 armv7l GNU/Linux
p

#### Expected behaviour
I use the ZeroSeg to display time and date with code from luma.led_matrix. It worked well with Buster operating system.

#### Actual behaviour
After installing "Bullseye" RPi operating system and attempting to run the luma.led_matrix code, I get the following error:
```
Traceback (most recent call last):
  File "/home/pi/luma7datetime.py", line 15, in <module>
    from luma.led_matrix.device import max7219
ModuleNotFoundError: No module named 'luma'

```
I tried to reinstall from https://luma-led-matrix.readthedocs.io/en/latest/install.html, but get the same error message. Help getting this fixed would be greatly appreciated.

**Comment by thijstriemstra** [comment] 2021-12-02 13:14
duplicate of #260

**Closed** 2021-12-02 13:14 UTC
