### ISSUE TITLE
luma.core 1.41.1 causes crash

### ISSUE THREAD

**Issue by tweiner** [rm-hull/luma.led_matrix#224] opened 2020-07-20 22:47 UTC
> Firstly thanks for taking the time to file an issue. Chances are, you are not the first (and
> wont be the last) to have this problem: By creating a public issue, others can browse and
> solve their issues - possibly in a self-service style - just by reading the discourse on your
> ticket, so try and be clear in the describing the problem you have.
>
> Secondly, github issues are not _just_ for raising problems - if you have a question, a
> documentation fix, or suggested improvement, please get in touch.
>
> Lastly, there are a number of related LUMA projects - please check to make sure to create
> the issue in the right GitHub repository.

#### Type of Raspberry Pi
> Not all Pi's are equal at the hardware level - what works on one, might not work on the next.
> This library has been tested on every variant except the RPi3.

#### Linux Kernel version
> Paste in the output from running `uname -a` at the command line on your Pi.

Linux raspberrypi1 5.4.51-v7+ #1326 SMP Fri Jul 17 10:45:25 BST 2020 armv7l GNU/Linux

#### Expected behaviour
> Add a few concise notes about what you are expecting to happen.
> Even better, if you paste in a code sample that demonstrates what you want to achieve.

updated from luma.led-matrix 1.4.1 to 1.5.0
that also updated luma.core from 1.0.0 to 1.14.0

started getting error at this line in my code
serial = spi(port=0, device=0, gpio=noop())

got this error

The debugged program raised the exception unhandled SystemError
"error return without exception set"
File: /home/pi/.local/lib/python3.7/site-packages/luma/core/interface/serial.py, Line: 285

downgraded luma.core back to 1.0.0

and everything is working like it used to.

#### Actual behaviour
> Now add some details about what actually happened - if there is an unexpected crash, paste in the
> [traceback info](https://www.google.com/search?q=python+traceback#q=What+is+a+traceback%3F).

I have a simple program that uses an ultrasonic distance sensor that at a certain distance starts a message on a 7219 matrix.

**Comment by thijstriemstra** [comment] 2020-07-20 23:21
duplicate of #220

**Closed by thijstriemstra** 2020-07-20 23:21 UTC
Labels: duplicate

**Comment by tweiner** [comment] 2020-07-21 00:40
thanks
